name: release-stage-monolith-java

on:
  workflow_dispatch:

jobs:
  release:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    # - name: Set up JDK 24
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: '24'
    #     distribution: 'temurin'

    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@v4.0.0

    # - name: Make Gradle Wrapper executable
    #   run: chmod +x ./gradlew

    - name: Release System
      run: docker compose -f docker-compose.monolith-java.yml up -d
      # NOTE: In real life applications, you'd be deploying your System to some Environment
      # For this demo application, I'm using Docker Compose

    - name: Destroy System
      run: docker compose -f docker-compose.monolith-java.yml down
      # NOTE: In real life applications, this wouldn't be done



    # - name: Setup Acceptance Environment for Acceptance Tests
    #   run: docker compose -f docker-compose.acc.yml up -d
    #   # NOTE: In real life applications, you'd be deploying your System to Acceptance Environment
    #   # For this demo application, I'm using Docker Compose

    # - name: Run Acceptance Tests
    #   run: ./gradlew test --tests com.optivem.eshop.acc.acceptance.*

    # - name: Run External System Contract Tests (targeting External System Stubs)
    #   run: ./gradlew test --tests com.optivem.eshop.acc.external.stub.*

    # - name: Destroy Acceptance Test Environment
    #   run: docker compose -f docker-compose.acc.yml down
    #   # Note: In real life applications, your choice whether to have transient or permament
    #   # Here I destroyed it due to Docker Compose

    # - name: Setup Acceptance Environment for E2E Tests
    #   run: docker compose -f docker-compose.e2e.yml up -d
    #   # NOTE: In real life applications, you'd be deploying your System to Acceptance Environment
    #   # For this demo application, I'm using Docker Compose

    # - name: Run External System Contract Tests (targeting External System Test Instances)
    #   run: ./gradlew test --tests com.optivem.eshop.acc.external.real.*

    # - name: Run E2E Tests
    #   run: ./gradlew test --tests com.optivem.eshop.e2e.*

    # - name: Destroy Acceptance Test Environment
    #   run: docker compose -f docker-compose.e2e.yml down
    #   # Note: In real life applications, your choice whether to have transient or permament
    #   # Here I destroyed it due to Docker Compose