# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: system-monolith-csharp

on:
  push:
    branches: [ "main" ]
    paths:
        - 'system/monolith/csharp/**'
        - '.github/workflows/system-monolith-csharp.yml'
  pull_request:
    branches: [ "main" ]
    paths:
        - 'system/monolith/csharp/**'
        - '.github/workflows/system-monolith-csharp.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: system/monolith/csharp

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
